coreos/stream-metadata-go

release/release.go
Now that we split the packages, fix the resulting golint
warnings about `release.ReleaseArch` "stuttering".
=> release: Remove `Release` prefix on types

release/release_test.go, release/translate.go
This drains the primary logic from https://github.com/coreos/fedora-coreos-stream-generator
into this repo, so it can be more easily shared with coreos-assembler.
=> release: Add a ToStreamArchitectures API

stream/stream_test.go, stream/stream_utils.go
In updating openshift-install to use this I really wanted to have
nice error prefixing if a particular architecture/region wasn't
found.  These new APIs handle that and also are what basically
everyone interacting with AWS will want.
(I may update the example to use them in the future, but it's
also useful to show traversing the "raw" data structures)
=> stream: Add helper APIs for AWS

stream/stream_test.go, stream/stream_utils.go
I actually also want this for e.g. GCP, let's just make the
API public so it's easy to use outside.
=> stream: Make FormatPrefix public

release/release.go, release/translate.go, stream/stream.go
Moving this from
https://github.com/coreos/coreos-assembler/pull/2000#issuecomment-763152177
I'm trying to port openshift-install to streams, and it currently
is using the uncompressed sha256 - and further it's exposed in
some cases to users.
Since compression isn't always easily reproducible, I think what
cosa is doing in having both checksums is a good thing; might
as well do belt-and-suspenders.
To emphasize we already have this data from the cosa
metadata, this is just adding support for it to the stream
and release metadata.
=> Add an uncompressed sha256 to release and streams

Makefile, arch/arch.go, arch/arch_test.go
Many users of this package will want to translate between
Go and RPM architectures.  This moves code that exists
in coreos-assembler (and can then be deleted from there):
https://github.com/coreos/coreos-assembler/blob/master/mantle/system/arch.go
=> Add an `arch` package

stream/stream.go
There's lots of artifacts (like the initramfs and rootfs) which don't
have this field in the original `meta.json`. We don't want to emit
`UncompressedSha256` keys for those.
=> stream: use omitempty for new UncompressedSha256

Makefile, release/release.go, release/rhcos/rhcos.go, release/translate.go, stream/rhcos/rhcos.go, stream/stream.go
This contains just a URL for now because that's all
the current RHCOS cosa metadata has.  I'm trying
to add e.g. the Azure Blob storage md5 information as
well as the full size+sha256, but in practice this
data is just the uncompressed VHD; anyone who wants
to do "offline" verification outside of Azure can
replicate that.
For FCOS we may end up uploading the image too,
though we hope there to end up in the Marketplace.
For now, let's stick this off an explicit extension area.
Closes: https://github.com/coreos/stream-metadata-go/issues/13
=> Add RHELCoreOSExtensions with Azure image URL

stream/stream_test.go, stream/stream_utils.go
Came up in review of https://github.com/openshift/installer/pull/4582#discussion_r582452663
Since error prefixing will use `:`, let's avoid ambiguity.  It's
going to be generally obvious from context what a stream name
and architecture are (particularly the architecture, everyone
knows `x86_64` and `aarch64` if they're provisioning a machine
for them).
=> FormatPrefix: Just use <streamname>/<arch>

stream/stream_test.go, stream/stream_utils.go
Almost everything *except* `metal` is a disk, so this little
query API is convenient, plus traversing the chain requires
verbose error handling for callers that they shouldn't
need to replcate.
=> stream: Add a high level API to find a disk

example/example.go, go.mod, go.sum, stream/artifact_utils.go, vendor/github.com/google/renameio/.golangci.yml, vendor/github.com/google/renameio/CONTRIBUTING.md, vendor/github.com/google/renameio/LICENSE, vendor/github.com/google/renameio/README.md, vendor/github.com/google/renameio/doc.go, vendor/github.com/google/renameio/go.mod, vendor/github.com/google/renameio/tempfile.go, vendor/github.com/google/renameio/writefile.go, vendor/modules.txt
Ideally of course we'd validate the GPG signatures too but
that runs into the problem of us shipping the keys in this
library or depending on them externally.
I'd also like to add the size to the stream metadata, because
it allows e.g. detecting the case when a server is feeding us
too much data (or too little).
Will circle back to that later.
=> artifact: Add a method to download+validate checksum

stream/artifact_utils.go
When reading the URL we need to use `path` for Windows, but
local files are `filepath`.
=> Download: Fix path/filepath mixup

example/example.go
=> example: use new QueryDisk API

stream/artifact_utils.go, stream/stream_test.go
Depends https://github.com/coreos/stream-metadata-go/pull/22
This is a generally useful utilty that we can factor out of
the `Download()` API.
=>  artifact: Add a Name() API

example/example.go, fedoracoreos/fcos.go
Most callers will want this.  Additionally, if we ever add
more integrity for the stream such as GPG signing, this will
be the place to do it.
xref https://github.com/coreos/fedora-coreos-tracker/issues/774
=> fedoracoreos: Add FetchStream API

.github/workflows/go.yml, go.sum
F33, F34, and OCP 4.9 have Go 1.15 or higher.
=> Drop EOL Go version, bump linter, restrict workflow access to repo

stream/fixtures/fcos-stream.json, stream/stream.go
Allow recording the software that generated the file.
Spec update: https://github.com/coreos/fedora-coreos-tracker/pull/962
=> stream: add `Metadata.Generator` field

stream/stream.go
RHCOS artifacts are not signed.  If we omit signature URLs from the stream metadata, we currently get a field with an empty string as a value.  Since artifacts will likely still be unsigned for a while, acquiesce to reality and correctly omit the field.
xref https://github.com/openshift/installer/pull/5268
=> stream: make `Artifact.Signature` omitempty

release/release.go, release/translate.go, stream/stream.go
Since the image name is version-specific, we should include a release field here to record the corresponding OS version.  Stream metadata supports version skew between different platforms (e.g. to avoid a platform-specific regression in a release) and we're generally explicit about the version of each artifact.
While we're here, drop `omitempty` from mandatory `GcpImage` fields.  It's harmless, but implies that they're optional.
=> stream: add release field to `GcpImage`

release/release.go, release/translate.go, stream/stream.go
Today we generate metadata for PowerVS in RHCOS, and we would need this to be updated in the installer in the near future, hence this change. IBMCloud and PowerVS have the same format although as of today there are no IBMCloud objects being generated. The naming here is to use "object" instead of image since these are not traditional bootimages like in other clouds.
FCOS is still waiting on ppc64le hardware to have P images generated so could not add any tests related to this.
=> Add support for IBMCloud/PowerVS images

.github/workflows/go.yml
To reduce CI resources, skip linting on both platforms, and test both only on the latest supported Go.
=> workflows: build and test on macOS and Windows

stream/stream.go
* Remove `omitempty` from Image string
* Restore alphabetical order in the Images struct
=> Minor cleanups on kubevirt related structs

example/example.go, release/release.go, release/translate.go, stream/fixtures/fcos-stream.json, stream/stream.go, stream/stream_utils.go
Every stream image should have a `Release` field for occasions when the recommended images aren't all at the same release.  That brings the KubeVirt structs in line with the standard ones, so just switch to those.  This is technically a compatibility break, but KubeVirt is new.
In the process, rename `RegionImage` and `RegionObject` to `SingleImage` and `SingleObject`, so they can be used on platforms with globally-namespaced images/objects.
cc @rmohr
=> Use generic structs for KubeVirt; rename `Region*` to `Single*`

release/release.go, release/translate.go
Going through steps to add virtualbox to a supported type for our offical release as per https://github.com/coreos/fedora-coreos-tracker/issues/1008
=> Add VirtualBox artifact to stream and release metadata

release/release.go, release/translate.go, stream/fixtures/fcos-stream.json, stream/stream.go, stream/stream_test.go
In the current design, the KubeVirt image is presumed to be a fully-qualified reference, including a container digest.  But that implies that the user should reference the image by digest, when we'd prefer that they reference it by stream-specific tag.
Define the existing `image` field to contain the preferred form of fully-qualified reference for the image, which might involve either a
tag or a digest.  We should still record the unique identifier of the current image (as we do for GCP images), so add a `digest-ref` field which always contains a fully-qualified reference with digest.
cc @rmohr @dustymabe
=> Add digest reference to KubeVirt image description

.github/workflows/go.yml, go.mod
=> Bump minimum Go version to 1.18

release/fixtures/fcos-release.json, stream/fixtures/fcos-stream.json, stream/stream_test.go
Seeing that we get an `ociarchive` artifact after we `cosa buildextend-kubevirt`, we need to update the format in the `fcos-release.json` and `fcos-stream.json` in addition to stream_test.go.
=> Update kubevirt platform format

docs/release-notes.md, release/release.go, release/translate.go
Following new platform support checklist for Hyperv
https://github.com/coreos/fedora-coreos-tracker/issues/1424
=> Add Hyper-V artifact

docs/release-notes.md, release/release.go, release/translate.go
Satisfying coreos/fedora-coreos-tracker#1533 and
coreos/fedora-coreos-tracker#1548
=> Add AppleHV artifact to stream and release metadata

docs/release-notes.md, release/fixtures/fcos-release.json, release/fixtures/fcos-releases.json, release/release.go, release/release_test.go
Add support in both release metadata and the release index for specifying OCI image pullspecs for a given release. In both cases, the new fields are located at the same level as the existing `commits` key holding OSTree checksums.
The key is called `oci-image` in release metadata and `oci-images` in the release index.
Part of https://github.com/coreos/fedora-coreos-tracker/issues/1823.
=> release: support OCI image pullspecs

docs/release-notes.md, release/rhcos/rhcos.go, release/translate.go, stream/rhcos/rhcos.go
Add image information for AWS Windows License Included images to both
release and stream RHELCoreOSExtensions structs. Also add logic to
translate the AWS WinLI release metadata into stream metadata.
See: https://issues.redhat.com/browse/COS-3057
This is needed before https://github.com/coreos/coreos-assembler/pull/4069 lands
=> Add AWS WinLI images to RHELCoreOSExtensions

docs/release-notes.md, stream/rhcos/rhcos.go
Adds a marketplace extension to contain cloud marketplace offerings, which would be updated by a separate process (than the rhcos.json stream publishing). Initially, the API is only defined for Azure, but AWS & GCP will be subsequently added.
See https://github.com/openshift/enhancements/pull/1655 for more details and discussion.
=> Add marketplace extension

docs/release-notes.md, release/release.go
FCOS at least doesn't ship using OSTree anymore, so allow the field to be empty.
=> release: support missing ostree commits
